<a href="https://colab.research.google.com/github/deepshikharbhardwaj/Machine_Learning/blob/main/PyTorch_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

# Basics

Tensor should take ONLY 1 Argument

In [ ]:
my_tensor = torch.tensor([1,2,3],[4,5,6])

TypeError: ignored

In [ ]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]])
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]] ,dtype = torch.float32)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1,2,3],[4,5,6]] ,dtype = torch.float32, device=device)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [ ]:

my_tensor = torch.tensor([[1,2,3],[4,5,6]] ,dtype = torch.float32, device=device, requires_grad=True)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

In [ ]:
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)

torch.float32
cuda:0
torch.Size([2, 3])


# Torch Initialisation

In [ ]:
x = torch.empty(size = (3,3))
x

tensor([[-1.3166e+29,  3.0922e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  0.0000e+00],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22]])

In [ ]:
x = torch.zeros(size = (3,3)) #OR x = torch.empty((3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
x = torch.ones((3,3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
x = torch.rand((3,3)) #UNIFORM DISTRIBUTION
x

tensor([[0.2238, 0.8675, 0.5901],
        [0.0357, 0.8331, 0.9299],
        [0.9802, 0.5866, 0.7941]])

In [ ]:
x = torch.eye(3) # OR x = torch.eye((3,3))
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
x = torch.arange(start = 0, end = 10, step = 1)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x = torch.linspace( 0.1,  1,  10)#start,end, steps
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [ ]:
x = torch.empty(size = (1,5)).normal_( mean = 0, std = 1)
x

tensor([[-0.6455, -1.7216, -0.1668, -1.1562,  0.5247]])

In [ ]:
x = torch.empty(size = (3,3)).uniform_( 0, 1)
x

tensor([[0.5319, 0.0499, 0.6945],
        [0.7826, 0.7402, 0.2328],
        [0.1461, 0.5970, 0.7123]])

In [ ]:
x = torch.diag(torch.rand(3))
x

tensor([[0.7990, 0.0000, 0.0000],
        [0.0000, 0.0718, 0.0000],
        [0.0000, 0.0000, 0.2725]])

# Initialize and convert Tensors to different types

In [ ]:
tensor = torch.arange(4)
tensor

tensor([0, 1, 2, 3])

In [ ]:
print(tensor.bool())

tensor([False,  True,  True,  True])


In [ ]:
print(tensor.short())

tensor([0, 1, 2, 3], dtype=torch.int16)


In [ ]:
print(tensor.long())

tensor([0, 1, 2, 3])


In [ ]:
print(tensor.half())

tensor([0., 1., 2., 3.], dtype=torch.float16)


In [ ]:
print(tensor.float())

tensor([0., 1., 2., 3.])


In [ ]:
print(tensor.double())

tensor([0., 1., 2., 3.], dtype=torch.float64)


# Numpy and Tensor Interconversion

In [ ]:
np_array = np.zeros((5,5))
tensor = torch.from_numpy(np_array)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [ ]:
np_array_back = tensor.numpy()
np_array_back

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Mathematics

In [ ]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])
add = x + y
sub = x - y
div = torch.true_divide(x,y)
div

tensor([0.1111, 0.2500, 0.4286])

In [ ]:
t = torch.zeros(3)
t.add_(x)
t += x #INPLACE ADDITION
t = t + x # NORMAL ADDITION

In [ ]:
z = x.pow(2) # OR x**2
z

tensor([1, 4, 9])

In [ ]:
#MATRIX MULTIPLICATION
a = torch.tensor([ 1, 2, 3])
b = torch.tensor([ 10, 10, 10 ])
x = a.matmul(b) # tensor.dot(a,b) same results
x

tensor(60)

In [ ]:
x = a * b
x

tensor([10, 20, 30])

In [ ]:
a1 = torch.tensor(( [[ 1, 2, 3], [4,5,6]] ))
b1 = torch.tensor(( [[ 10, 10, 10 ], [10, 10, 10], [10,10,10]] ))
x = a1.matmul(b1)
x

tensor([[ 60,  60,  60],
        [150, 150, 150]])

In [ ]:
z = torch.dot(a,b)
z

tensor(60)

In [ ]:
#BATCH MATRIX MULTIPLICATION
batch = 32
n = 10
m = 20
p = 30

tensor1 =  torch.rand((batch, n , m))
tensor2 =  torch.rand((batch, m , p))
out_bmm = torch.bmm(tensor1, tensor2) #(batch, n, p)
out_bmm

tensor([[[5.6332, 5.5514, 3.8227,  ..., 4.6969, 5.6156, 4.1307],
         [4.5636, 4.7153, 4.0245,  ..., 4.3428, 4.9982, 3.8089],
         [5.2167, 5.2118, 3.5934,  ..., 5.1266, 5.0450, 3.8832],
         ...,
         [6.7659, 6.2725, 4.7783,  ..., 5.6165, 6.5834, 5.1801],
         [6.4199, 6.3950, 4.3163,  ..., 4.5658, 5.9025, 4.8469],
         [7.4118, 5.8483, 5.0017,  ..., 5.7673, 6.8417, 4.9878]],

        [[3.9765, 3.1785, 2.6704,  ..., 3.4773, 3.0908, 3.2122],
         [4.7914, 3.9944, 4.0346,  ..., 4.9064, 3.5971, 4.1767],
         [5.8063, 4.8159, 3.9691,  ..., 5.6358, 4.7999, 3.9452],
         ...,
         [6.1249, 6.0720, 4.9092,  ..., 6.3594, 5.2976, 5.1142],
         [3.1861, 3.6027, 2.7533,  ..., 4.4394, 3.8670, 2.5754],
         [7.0675, 5.2412, 4.6386,  ..., 5.5422, 5.1637, 5.1200]],

        [[4.8253, 3.6978, 6.8449,  ..., 5.4753, 4.5636, 6.0165],
         [4.5383, 3.4044, 6.1263,  ..., 5.4497, 4.1600, 4.9159],
         [5.6972, 4.1260, 7.0617,  ..., 6.2003, 4.9594, 6.

In [ ]:
a1 = torch.tensor(( [[ 1, 2, 3], [4,5,6], [7,8,9]] ))
print(a1)
sum = torch.sum(a1,dim=0) #vertically top-bottom
print(sum)
sum = torch.sum(a1,dim=1) #horizontally left-right
print(sum)
#sum = torch.sum(a2,dim=2)
#print(sum)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([12, 15, 18])
tensor([ 6, 15, 24])


In [ ]:
#MAX
values, indices = torch.max(a1, dim=0)
print(values, indices)

tensor([7, 8, 9]) tensor([2, 2, 2])


In [ ]:
mean = torch.mean(a1,dim = 0) #a1 should be float
mean

RuntimeError: ignored

In [ ]:
mean = torch.mean(a1.float(),dim = 0)
mean

tensor([4., 5., 6.])

In [ ]:
sorted_a1, indices = torch.sort(a1, descending=True)
print(a1,'\n', sorted_a1,'\n', indices)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 
 tensor([[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]]) 
 tensor([[2, 1, 0],
        [2, 1, 0],
        [2, 1, 0]])


In [ ]:
z = torch.clamp(a1, min = 2, max = 8) # min value - below that all min , max - all above max set to max
z

tensor([[2, 2, 3],
        [4, 5, 6],
        [7, 8, 8]])

#Batch Indexing

In [ ]:
batch_size = 10
features = 25
x = torch.rand(batch_size, features)
x

tensor([[0.1233, 0.7616, 0.2860, 0.3810, 0.2315, 0.0934, 0.0859, 0.0848, 0.5353,
         0.5407, 0.7639, 0.3725, 0.8877, 0.7014, 0.2788, 0.4184, 0.9879, 0.5155,
         0.6070, 0.5926, 0.6255, 0.0871, 0.5081, 0.0912, 0.0087],
        [0.6630, 0.0073, 0.6622, 0.3281, 0.2814, 0.0640, 0.7587, 0.2742, 0.7908,
         0.5693, 0.5132, 0.0506, 0.5501, 0.5096, 0.8167, 0.6739, 0.0034, 0.5665,
         0.2167, 0.9020, 0.4173, 0.0255, 0.7566, 0.1186, 0.5642],
        [0.9391, 0.2618, 0.8121, 0.7745, 0.1985, 0.9600, 0.5855, 0.2491, 0.0096,
         0.1526, 0.2860, 0.6275, 0.8537, 0.4389, 0.5719, 0.7720, 0.9964, 0.0383,
         0.7094, 0.0945, 0.7530, 0.9171, 0.0718, 0.8014, 0.0109],
        [0.2761, 0.7304, 0.3388, 0.0443, 0.0391, 0.8253, 0.8288, 0.7623, 0.8417,
         0.6676, 0.6609, 0.5478, 0.4323, 0.9565, 0.6630, 0.6117, 0.7722, 0.3480,
         0.7256, 0.2970, 0.1895, 0.9253, 0.5987, 0.7206, 0.4352],
        [0.0216, 0.3211, 0.5846, 0.3701, 0.4889, 0.4918, 0.3811, 0.3921, 0.9409,
       

In [ ]:
x = torch.arange(10,20)
print(x[(x<12) | (x > 18)])

tensor([10, 11, 19])


In [ ]:
x[[2,4,6]]

tensor([12, 14, 16])

In [ ]:
x

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
x[[2]]

tensor([12])

In [ ]:
x[2]

tensor(12)

In [ ]:
x[x.remainder(2)==0]

tensor([10, 12, 14, 16, 18])

In [ ]:
torch.where(x>12,x,x*2)

tensor([20, 22, 24, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
torch.tensor([1,1,2,2,2,3,3,1,1,1,1,2]).unique()

tensor([1, 2, 3])

In [ ]:
x.ndimension()

1

#Reshaping Tensor

In [2]:
x = torch.arange(9)
xr = x.view(3,3) #work for contiguous memory
xr

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [3]:
xr = x.reshape(3,3) #works everytime but not efficient as view , but for safe option use reshape
xr

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [4]:
x1  = torch.rand(2,5)
x2  = torch.rand(2,5)
torch.cat((x1,x2), dim = 0).shape

torch.Size([4, 5])

In [7]:
#flatten the matrix
z = x1.reshape(-1)
z

tensor([0.1659, 0.7694, 0.1647, 0.7959, 0.4782, 0.7871, 0.2076, 0.1199, 0.8039,
        0.3764])

In [8]:
z.shape

torch.Size([10])

In [9]:
#IMPORTANT WITH BATCH
batch = 64
x = torch.rand(batch,2,5)
y = x.reshape(batch,-1) #i.e. when i dont want to touch batch
y.shape

torch.Size([64, 10])

In [10]:
#IMPORTANT CHANGING THE AXIS
z = x.permute(0,2,1)
z.shape

torch.Size([64, 5, 2])

In [19]:
#IMPORTANT UNSQUEEZE
x = torch.arange(10) #shape -> [10]
print(x.shape)
print(x.unsqueeze(0).shape) #at 0th index 
print(x.unsqueeze(1).shape) #at 1th index
z = x.unsqueeze(0).unsqueeze(1)
print(x.unsqueeze(0).unsqueeze(1).shape) #at 0th and 1th index

#Now we dont want 1th index
z = z.squeeze(1)
print(z.shape)

torch.Size([10])
torch.Size([1, 10])
torch.Size([10, 1])
torch.Size([1, 1, 10])
torch.Size([1, 10])
